name: weather_app_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  flutter_dotenv: ^5.1.0
  recase: ^4.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  custom_lint:
  
  build_runner:
  freezed:
  json_serializable:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/